name: Publish to Google Play Console Internal Track

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

env:
  APP_VERSION_NUMBER: ${{ github.run_number }}
  FOODTRACKER_KEYSTORE_FILE: keystore.jks
  FOODTRACKER_GRADLE_PUBLISHER_CREDENTIALS_FILE: service-account-gpp.json

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Print RUN_ID
        run: echo THE RUN ID $RUN_ID

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'gradle'

      - name: Grant execute permissions to gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew testDebug

  playstore:
    name: Release to playstore internal track
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Grant execute permissions to gradlew
        run: chmod +x gradlew

      - name: Setup keystore
        run: 'echo "$E_FOODTRACKER_KEYSTORE_FILE" | base64 -d > app/keystore.jks'
        env:
          E_FOODTRACKER_KEYSTORE_FILE: ${{ secrets.E_FOODTRACKER_KEYSTORE_FILE }}

      - name: Setup Google Play credential file
        run: 'echo "$E_FOODTRACKER_GRADLE_PUBLISHER_CREDENTIALS_FILE" | base64 -d > app/service-account-gpp.json'
        env:
          E_FOODTRACKER_GRADLE_PUBLISHER_CREDENTIALS_FILE: ${{ secrets.E_FOODTRACKER_GRADLE_PUBLISHER_CREDENTIALS_FILE }}

      # It's internal track because it's gradle-play-plugin default track, but be careful,
      # depending on the configuration this job name could be a lie, always double check command
      # and gradle related files. If it shouldn't get published to production it is also a good
      # idea to ONLY give internal track permissions for the service account
      - name: Build and upload AAB to Google Play Console internal track
        run: ./gradlew publishBundle
        env:
          FOODTRACKER_KEYSTORE_PWD: ${{ secrets.FOODTRACKER_KEYSTORE_PWD }}
          FOODTRACKER_KEY_ALIAS: ${{ secrets.FOODTRACKER_KEY_ALIAS }}
          FOODTRACKER_KEY_PWD: ${{ secrets.FOODTRACKER_KEY_PWD }}
